site_name: WEGA-project
theme:
  # features:
  #   - header.autohide
  name: material
  favicon: "assets/favicon.ico"
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
      primary: green
      accent: blue

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
      primary: green
      accent: teal
  font:
    text: Ubuntu
  icon:
    logo: material/cloud
markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

plugins:
  - search:
      lang: ru
  - glightbox:
      touchNavigation: false
      loop: false
      effect: zoom
      width: 100%
      height: auto
      zoomable: true
      draggable: true
      skip_classes:
        - custom-skip-class-name
      auto_caption: false
      caption_position: bottom
nav:
  - Описание: "index.md"
  - WEGA Server:
      - Как настроить: "server/install.md"
      - Установка через скрипт: "server/auto_install.md"
      - Ручная установка: "server/manual_install.md"
  - WEGABOX:
      - Описание: "box/box.md"
